import { AppState, AssumptionsState, ProjectRecord, QuantityTakeoffItem } from '../types';

export const DEFAULT_ASSUMPTIONS: AssumptionsState = {
  currencySymbol: '$',
  overheadRate: 0.10, // 10.0%
  targetMarkupRate: 0.15, // 15.0%
  contingencyRate: 0.05, // 5.0%
  laborRates: [
    { id: 'LR-1', tradeName: 'Plumbing - Journeyman', ratePerHour: 88.50, description: 'Licensed commercial plumber' },
    { id: 'LR-2', tradeName: 'Plumbing - Apprentice', ratePerHour: 52.00, description: 'Registered plumbing apprentice' },
    { id: 'LR-3', tradeName: 'HVAC - Senior Tech', ratePerHour: 92.00, description: 'EPA certified HVAC mechanic' },
    { id: 'LR-4', tradeName: 'HVAC - Sheet Metal Journeyman', ratePerHour: 84.00, description: 'Duct fabrication & installer' },
    { id: 'LR-5', tradeName: 'Pipefitter / Certified Welder', ratePerHour: 98.00, description: 'ASME high-pressure certified' },
    { id: 'LR-6', tradeName: 'Insulator - Mechanical Systems', ratePerHour: 72.00, description: 'Thermal & acoustic pipe lagging' },
    { id: 'LR-7', tradeName: 'Controls & Commissioning Tech', ratePerHour: 105.00, description: 'BAS / DDC integration engineer' },
    { id: 'LR-8', tradeName: 'General MEP Laborer', ratePerHour: 45.00, description: 'Site staging & cleanup crew' },
  ],
  equipmentRates: [
    { id: 'EQ-1', equipmentType: 'Scissor Lift 26ft Electric', ratePerHour: 28.00, description: 'Indoor elevated rough-in' },
    { id: 'EQ-2', equipmentType: 'Boom Lift 45ft All-Terrain', ratePerHour: 55.00, description: 'High bay piping & exhaust work' },
    { id: 'EQ-3', equipmentType: 'Mini Excavator & Shoring', ratePerHour: 95.00, description: 'Underground sanitary trenching' },
    { id: 'EQ-4', equipmentType: 'Electric Pipe Threader 4"', ratePerHour: 18.00, description: 'Rigid steel pipe threading' },
    { id: 'EQ-5', equipmentType: 'ProPress / MegaPress Tooling', ratePerHour: 14.00, description: 'Hydraulic copper/steel crimping' },
    { id: 'EQ-6', equipmentType: 'Mobile Crane 40-Ton (Rigging)', ratePerHour: 220.00, description: 'Rooftop AHU & Chiller pick' },
    { id: 'EQ-7', equipmentType: 'Hydrostatic Test Pump Unit', ratePerHour: 15.00, description: 'Pressure testing & cert rig' },
  ],
};

export const DEFAULT_PROJECTS: ProjectRecord[] = [
  {
    id: 'PRJ-2026-001',
    name: 'Metro Regional Hospital Surgical Pavilion',
    client: 'Apex Healthcare Builders Ltd.',
    bidDate: '2026-03-15',
    estimator: 'Marcus Vance, CPE',
    status: 'Won',
    notes: 'Includes medical gas certified piping, acid waste neutralization, and domestic hot water recirc system.',
  },
  {
    id: 'PRJ-2026-002',
    name: 'Silicon Hub Phase 3 Data Center Cooling',
    client: 'Turner-Vanguard Joint Venture',
    bidDate: '2026-04-10',
    estimator: 'Elena Rostova, PE',
    status: 'Submitted',
    notes: 'Dual chilled water risers, CRAC units connection, 8" welded schedule 40 headers with seismic restraints.',
  },
  {
    id: 'PRJ-2026-003',
    name: 'Cascade Central High School Modernization',
    client: 'District 408 Public Schools',
    bidDate: '2026-02-28',
    estimator: 'David K. Chen',
    status: 'Won',
    notes: 'Complete hydronic boiler plant replacement, VRF split units, and student restroom bank fixture overhaul.',
  },
  {
    id: 'PRJ-2026-004',
    name: 'Skyline Luminary 38-Story Mixed-Use Tower',
    client: 'Pinnacle Development Group',
    bidDate: '2026-05-20',
    estimator: 'Marcus Vance, CPE',
    status: 'Pending',
    notes: 'Gravity sanitary risers, cast iron storm roof drains, high-pressure domestic booster pumps.',
  },
  {
    id: 'PRJ-2026-005',
    name: 'Gateway International Airport Concourse D',
    client: 'Metropolitan Aviation Authority',
    bidDate: '2026-01-20',
    estimator: 'Elena Rostova, PE',
    status: 'Lost',
    notes: 'Lost due to aggressive non-union general contractor bidding 6.5% lower on ductwork fabrication.',
  },
  {
    id: 'PRJ-2026-006',
    name: 'BioGen Discovery Wet Research Laboratory',
    client: 'NovaCore Life Sciences',
    bidDate: '2026-06-05',
    estimator: 'David K. Chen',
    status: 'Draft',
    notes: 'High-purity DI water loop, lab gas manifolds, emergency eyewash/deluge shower loops.',
  },
];

export const DEFAULT_TAKEOFFS: QuantityTakeoffItem[] = [
  // Project 1: Metro Hospital (PRJ-2026-001)
  {
    id: 'TO-101',
    projectId: 'PRJ-2026-001',
    division: 'Plumbing - Journeyman',
    itemDescription: '4" Type L Copper Domestic Water Main (Soldered & Victaulic)',
    unit: 'LF',
    quantity: 1450,
    materialUnitRate: 34.50,
    laborHoursPerUnit: 0.85,
    equipmentUnitRate: 4.20,
  },
  {
    id: 'TO-102',
    projectId: 'PRJ-2026-001',
    division: 'Plumbing - Journeyman',
    itemDescription: 'Cast Iron No-Hub 6" Sanitary Waste & Vent Piping',
    unit: 'LF',
    quantity: 2100,
    materialUnitRate: 28.00,
    laborHoursPerUnit: 0.95,
    equipmentUnitRate: 5.50,
  },
  {
    id: 'TO-103',
    projectId: 'PRJ-2026-001',
    division: 'Pipefitter / Certified Welder',
    itemDescription: 'NFPA 99 Medical Gas Copper Piping (O2, Med-Air, Vacuum)',
    unit: 'LF',
    quantity: 3800,
    materialUnitRate: 42.00,
    laborHoursPerUnit: 1.10,
    equipmentUnitRate: 6.80,
  },
  {
    id: 'TO-104',
    projectId: 'PRJ-2026-001',
    division: 'Plumbing - Journeyman',
    itemDescription: 'Commercial Sensor Flushometer Water Closets & Sinks',
    unit: 'EA',
    quantity: 76,
    materialUnitRate: 480.00,
    laborHoursPerUnit: 3.50,
    equipmentUnitRate: 0.00,
  },
  {
    id: 'TO-105',
    projectId: 'PRJ-2026-001',
    division: 'Insulator - Mechanical Systems',
    itemDescription: 'Fiberglass Pipe Insulation with All-Service Jacket (ASJ)',
    unit: 'LF',
    quantity: 5250,
    materialUnitRate: 6.80,
    laborHoursPerUnit: 0.25,
    equipmentUnitRate: 1.50,
  },

  // Project 2: Silicon Hub Data Center (PRJ-2026-002)
  {
    id: 'TO-201',
    projectId: 'PRJ-2026-002',
    division: 'Pipefitter / Certified Welder',
    itemDescription: '8" Schedule 40 Carbon Steel Chilled Water Supply & Return Header',
    unit: 'LF',
    quantity: 2400,
    materialUnitRate: 68.00,
    laborHoursPerUnit: 1.45,
    equipmentUnitRate: 14.00,
  },
  {
    id: 'TO-202',
    projectId: 'PRJ-2026-002',
    division: 'HVAC - Senior Tech',
    itemDescription: 'CRAC Unit Dual Cooling Coil Connection & Balancing Valves',
    unit: 'EA',
    quantity: 24,
    materialUnitRate: 1850.00,
    laborHoursPerUnit: 12.00,
    equipmentUnitRate: 8.50,
  },
  {
    id: 'TO-203',
    projectId: 'PRJ-2026-002',
    division: 'Controls & Commissioning Tech',
    itemDescription: 'BACnet DDC Flow Meters, BTU Transmitters & Modulating Actuators',
    unit: 'SET',
    quantity: 18,
    materialUnitRate: 2400.00,
    laborHoursPerUnit: 8.00,
    equipmentUnitRate: 0.00,
  },
  {
    id: 'TO-204',
    projectId: 'PRJ-2026-002',
    division: 'Insulator - Mechanical Systems',
    itemDescription: '2" Closed-Cell Elastomeric Armaflex Chilled Water Insulation',
    unit: 'LF',
    quantity: 4800,
    materialUnitRate: 12.50,
    laborHoursPerUnit: 0.35,
    equipmentUnitRate: 2.20,
  },

  // Project 3: Cascade Central High School (PRJ-2026-003)
  {
    id: 'TO-301',
    projectId: 'PRJ-2026-003',
    division: 'HVAC - Senior Tech',
    itemDescription: 'High-Efficiency Condensing Hydronic Boilers 2,000 MBH',
    unit: 'EA',
    quantity: 3,
    materialUnitRate: 38000.00,
    laborHoursPerUnit: 48.00,
    equipmentUnitRate: 65.00,
  },
  {
    id: 'TO-302',
    projectId: 'PRJ-2026-003',
    division: 'HVAC - Sheet Metal Journeyman',
    itemDescription: 'Galvanized Rectangular Supply & Return Air Ductwork (Low/Med Press)',
    unit: 'SQFT',
    quantity: 18500,
    materialUnitRate: 7.20,
    laborHoursPerUnit: 0.18,
    equipmentUnitRate: 1.10,
  },
  {
    id: 'TO-303',
    projectId: 'PRJ-2026-003',
    division: 'Plumbing - Journeyman',
    itemDescription: 'Commercial Restroom Renovation: ADA Fixtures, Carriers & Trim',
    unit: 'EA',
    quantity: 42,
    materialUnitRate: 520.00,
    laborHoursPerUnit: 4.20,
    equipmentUnitRate: 0.00,
  },

  // Project 4: Skyline Luminary 38-Story Tower (PRJ-2026-004)
  {
    id: 'TO-401',
    projectId: 'PRJ-2026-004',
    division: 'Plumbing - Journeyman',
    itemDescription: '8" Heavy Cast Iron Sanitary & Storm Vertical Drainage Risers',
    unit: 'LF',
    quantity: 4200,
    materialUnitRate: 48.00,
    laborHoursPerUnit: 1.20,
    equipmentUnitRate: 12.50,
  },
  {
    id: 'TO-402',
    projectId: 'PRJ-2026-004',
    division: 'Pipefitter / Certified Welder',
    itemDescription: 'Triplex Variable Frequency Domestic Booster Pump Package',
    unit: 'SET',
    quantity: 2,
    materialUnitRate: 64000.00,
    laborHoursPerUnit: 64.00,
    equipmentUnitRate: 85.00,
  },
  {
    id: 'TO-403',
    projectId: 'PRJ-2026-004',
    division: 'Plumbing - Apprentice',
    itemDescription: 'PEX-a Commercial Water Distribution Risers with Multi-Port Tees',
    unit: 'LF',
    quantity: 12500,
    materialUnitRate: 6.20,
    laborHoursPerUnit: 0.16,
    equipmentUnitRate: 0.50,
  },

  // Project 5: Airport Concourse D (PRJ-2026-005)
  {
    id: 'TO-501',
    projectId: 'PRJ-2026-005',
    division: 'HVAC - Sheet Metal Journeyman',
    itemDescription: 'Double-Wall Acoustical Spiral Ductwork 36" Dia with Hangers',
    unit: 'LF',
    quantity: 3600,
    materialUnitRate: 54.00,
    laborHoursPerUnit: 0.75,
    equipmentUnitRate: 6.00,
  },
  {
    id: 'TO-502',
    projectId: 'PRJ-2026-005',
    division: 'Pipefitter / Certified Welder',
    itemDescription: 'Rooftop Packaged Air Handling Units (50 Ton) Rough-in & Piping',
    unit: 'EA',
    quantity: 6,
    materialUnitRate: 24500.00,
    laborHoursPerUnit: 52.00,
    equipmentUnitRate: 45.00,
  },

  // Project 6: BioGen Discovery Wet Lab (PRJ-2026-006)
  {
    id: 'TO-601',
    projectId: 'PRJ-2026-006',
    division: 'Plumbing - Journeyman',
    itemDescription: 'PVDF High-Purity Deionized Water Recirculation Loop',
    unit: 'LF',
    quantity: 1800,
    materialUnitRate: 58.00,
    laborHoursPerUnit: 1.30,
    equipmentUnitRate: 8.00,
  },
  {
    id: 'TO-602',
    projectId: 'PRJ-2026-006',
    division: 'Plumbing - Journeyman',
    itemDescription: 'Polypropylene Acid Waste & Neutralization Tank Package',
    unit: 'SET',
    quantity: 1,
    materialUnitRate: 32000.00,
    laborHoursPerUnit: 40.00,
    equipmentUnitRate: 35.00,
  },
];

export const DEFAULT_TRACKER_OVERRIDES: Record<string, { actualWonAmount: number; lossReason: string; status?: 'Draft' | 'Submitted' | 'Won' | 'Lost' | 'Pending' }> = {
  'PRJ-2026-001': {
    actualWonAmount: 645000.00,
    lossReason: '',
  },
  'PRJ-2026-003': {
    actualWonAmount: 495000.00,
    lossReason: '',
  },
  'PRJ-2026-005': {
    actualWonAmount: 0.00,
    lossReason: 'Low bidder priced sheet metal fabrication 6.5% below market union scale.',
  },
};

export const INITIAL_APP_STATE: AppState = {
  assumptions: DEFAULT_ASSUMPTIONS,
  projects: DEFAULT_PROJECTS,
  takeoffs: DEFAULT_TAKEOFFS,
  trackerOverrides: DEFAULT_TRACKER_OVERRIDES,
  selectedSummaryProjectId: 'PRJ-2026-001',
  lastSaved: new Date().toISOString(),
};
