import React from 'react';
import {
  FileCode2,
  Workflow,
  ShieldCheck,
  HelpCircle,
  ArrowRight,
  Database,
  Calculator,
  Sliders,
  FolderKanban,
  FileSpreadsheet,
  PieChart,
  BarChart3,
  CheckCircle2,
} from 'lucide-react';
import { SheetTabId } from '../../types';

interface Sheet01ReadmeProps {
  onNavigate: (tab: SheetTabId) => void;
}

export const Sheet01Readme: React.FC<Sheet01ReadmeProps> = ({ onNavigate }) => {
  return (
    <div className="space-y-8 animate-in">
      {/* Page Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <span className="text-[11px] font-mono uppercase tracking-label text-[var(--color-accent)] font-semibold">
            Sheet 01 // Documentation & Architecture
          </span>
          <h1 className="text-2xl lg:text-3xl font-bold font-heading text-[var(--color-primary)] tracking-display">
            Commercial Plumbing & Mechanical Estimating & Bid Tracking Excel Toolkit
          </h1>
          <p className="text-sm text-[var(--color-muted)] mt-1 max-w-3xl">
            A specialized institutional-grade SaaS estimating and tracking system designed for commercial mechanical,
            piping, and plumbing contractors. Standardizes engineering takeoff measurement, dynamic commercial markups,
            live multi-project rollup, and post-bid conversion analytics.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => onNavigate('02_Assumptions')}
            className="inline-flex items-center gap-1.5 px-4 py-2 bg-[var(--color-primary)] text-white text-xs font-semibold rounded-lg hover:opacity-90 transition shadow-sm cursor-pointer"
          >
            <span>Start with Assumptions</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Insight Highlight Block */}
      <div className="insight-block p-4 rounded-r-lg shadow-sm">
        <div className="flex items-start gap-3">
          <ShieldCheck className="w-5 h-5 text-[var(--color-accent)] shrink-0 mt-0.5" />
          <div>
            <h4 className="text-sm font-semibold text-[var(--color-primary)]">
              Real-Time Reactive Client-Side Formula Engine
            </h4>
            <p className="text-xs text-[var(--color-body-text)] mt-0.5 leading-relaxed">
              Every formula in this system operates reactively inside the browser. Adjusting any global assumption
              (such as Overhead % or Journeyman Labor Rate) or modifying a Takeoff line instantly cascades across the
              Calculation Engine, Project Summaries, Bid Pipeline Tracker, and Management Dashboard without requiring page reloads or manual calculation steps.
            </p>
          </div>
        </div>
      </div>

      {/* Color Code Legend Card */}
      <div className="bg-[var(--color-surface)] p-5 rounded-[var(--radius-lg)] shadow-[var(--shadow-sm)] border border-slate-100">
        <h3 className="text-sm font-bold font-heading text-[var(--color-primary)] uppercase tracking-label mb-3">
          Visual Interface Conventions & Legend
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="p-3 rounded-lg bg-[var(--color-bg)] flex items-start gap-3">
            <div className="w-6 h-6 rounded bg-[#FFFDE7] border border-amber-300 flex items-center justify-center shrink-0 text-[10px] font-bold text-amber-900">
              ✎
            </div>
            <div>
              <div className="text-xs font-semibold text-[var(--color-primary)]">Editable Input Cells</div>
              <div className="text-[11px] text-[var(--color-muted)]">Pale yellow background (#FFFDE7). Click or focus to modify.</div>
            </div>
          </div>

          <div className="p-3 rounded-lg bg-[var(--color-bg)] flex items-start gap-3">
            <div className="w-6 h-6 rounded bg-white border border-slate-300 flex items-center justify-center shrink-0 text-[10px] font-bold text-slate-700">
              fx
            </div>
            <div>
              <div className="text-xs font-semibold text-[var(--color-primary)]">Calculated Cells</div>
              <div className="text-[11px] text-[var(--color-muted)]">Read-only derived outputs strictly generated by math engine.</div>
            </div>
          </div>

          <div className="p-3 rounded-lg bg-[var(--color-bg)] flex items-start gap-3">
            <div className="w-6 h-6 rounded bg-[var(--color-accent)] flex items-center justify-center shrink-0 text-[10px] font-bold text-white">
              |||
            </div>
            <div>
              <div className="text-xs font-semibold text-[var(--color-primary)]">Inline Data Bars</div>
              <div className="text-[11px] text-[var(--color-muted)]">Solid accent bar with 10% opacity rail for instant scale assessment.</div>
            </div>
          </div>

          <div className="p-3 rounded-lg bg-[var(--color-bg)] flex items-start gap-3">
            <div className="w-6 h-6 rounded bg-red-100 border border-red-300 flex items-center justify-center shrink-0 text-[10px] font-bold text-red-700">
              !
            </div>
            <div>
              <div className="text-xs font-semibold text-[var(--color-primary)]">Action-Required Alert</div>
              <div className="text-[11px] text-[var(--color-muted)]">Reserved exclusively for threshold breaches or lost bid analysis.</div>
            </div>
          </div>
        </div>
      </div>

      {/* System Architecture & Workflow */}
      <div className="bg-[var(--color-surface)] p-6 rounded-[var(--radius-lg)] shadow-[var(--shadow-sm)] border border-slate-100">
        <h3 className="text-base font-bold font-heading text-[var(--color-primary)] mb-2 flex items-center gap-2">
          <Workflow className="w-4 h-4 text-[var(--color-accent)]" />
          End-to-End Workflow & Module Architecture
        </h3>
        <p className="text-xs text-[var(--color-muted)] mb-6">
          The application organizes data across 3 primary tiers and 8 coordinated sheets to maintain absolute separation between engineering facts and commercial strategy.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 relative">
          {/* Tier 1 */}
          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200/80 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-[11px] font-mono font-bold uppercase text-[var(--color-accent)]">Tier 1 // Input & Control</span>
              <Sliders className="w-4 h-4 text-slate-400" />
            </div>
            <div className="space-y-2">
              <div
                onClick={() => onNavigate('02_Assumptions')}
                className="p-2.5 bg-white rounded-lg shadow-sm border border-slate-200 hover:border-[var(--color-accent)] transition cursor-pointer"
              >
                <div className="text-xs font-semibold text-[var(--color-primary)]">[02] Global Assumptions</div>
                <div className="text-[11px] text-[var(--color-muted)]">Overhead %, Target Markup %, Contingency %, Trade Labor & Equipment standard rates.</div>
              </div>
              <div
                onClick={() => onNavigate('03_Project_Setup')}
                className="p-2.5 bg-white rounded-lg shadow-sm border border-slate-200 hover:border-[var(--color-accent)] transition cursor-pointer"
              >
                <div className="text-xs font-semibold text-[var(--color-primary)]">[03] Project Setup</div>
                <div className="text-[11px] text-[var(--color-muted)]">Master project register, client names, bid dates, estimators, and lifecycle status.</div>
              </div>
            </div>
          </div>

          {/* Tier 2 */}
          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200/80 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-[11px] font-mono font-bold uppercase text-[var(--color-accent)]">Tier 2 // Engine & Computation</span>
              <Calculator className="w-4 h-4 text-slate-400" />
            </div>
            <div className="space-y-2">
              <div
                onClick={() => onNavigate('04_Quantity_Takeoff')}
                className="p-2.5 bg-white rounded-lg shadow-sm border border-slate-200 hover:border-[var(--color-accent)] transition cursor-pointer"
              >
                <div className="text-xs font-semibold text-[var(--color-primary)]">[04] Quantity Takeoff</div>
                <div className="text-[11px] text-[var(--color-muted)]">Itemized bill of quantities, unit rates, labor hours per unit, and auto-applied trade rates.</div>
              </div>
              <div
                onClick={() => onNavigate('05_Estimate_Engine')}
                className="p-2.5 bg-white rounded-lg shadow-sm border border-slate-200 hover:border-[var(--color-accent)] transition cursor-pointer"
              >
                <div className="text-xs font-semibold text-[var(--color-primary)]">[05] Estimate Engine</div>
                <div className="text-[11px] text-[var(--color-muted)]">Pure dynamic cost engine: Direct Material, Labor, Equipment, Overhead, Contingency, Markup, Final Bid.</div>
              </div>
            </div>
          </div>

          {/* Tier 3 */}
          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200/80 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-[11px] font-mono font-bold uppercase text-[var(--color-accent)]">Tier 3 // Summary & Tracking</span>
              <BarChart3 className="w-4 h-4 text-slate-400" />
            </div>
            <div className="space-y-2">
              <div
                onClick={() => onNavigate('06_Bid_Summary')}
                className="p-2.5 bg-white rounded-lg shadow-sm border border-slate-200 hover:border-[var(--color-accent)] transition cursor-pointer"
              >
                <div className="text-xs font-semibold text-[var(--color-primary)]">[06] Bid Summary</div>
                <div className="text-[11px] text-[var(--color-muted)]">Single-project drill-down, labor cost ratios, and dynamic division breakdown table.</div>
              </div>
              <div
                onClick={() => onNavigate('07_Bid_Tracker')}
                className="p-2.5 bg-white rounded-lg shadow-sm border border-slate-200 hover:border-[var(--color-accent)] transition cursor-pointer"
              >
                <div className="text-xs font-semibold text-[var(--color-primary)]">[07] Bid Tracker</div>
                <div className="text-[11px] text-[var(--color-muted)]">Pipeline status, actual won amounts, contract variance, and loss post-mortem log.</div>
              </div>
              <div
                onClick={() => onNavigate('08_Dashboard')}
                className="p-2.5 bg-white rounded-lg shadow-sm border border-slate-200 hover:border-[var(--color-accent)] transition cursor-pointer"
              >
                <div className="text-xs font-semibold text-[var(--color-primary)]">[08] Executive Dashboard</div>
                <div className="text-[11px] text-[var(--color-muted)]">Executive KPIs, win rate by count/value, exposure matrix, and division distribution.</div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Standard Operating Procedure (SOP) */}
      <div className="bg-[var(--color-surface)] p-6 rounded-[var(--radius-lg)] shadow-[var(--shadow-sm)] border border-slate-100">
        <h3 className="text-base font-bold font-heading text-[var(--color-primary)] mb-4">
          Standard Operating Procedure (SOP) Guide
        </h3>

        <div className="space-y-4">
          {[
            {
              step: 'Step 1',
              title: 'Establish Commercial Assumptions',
              sheet: '02_Assumptions' as SheetTabId,
              desc: 'Configure corporate Overhead Rate (B5), Target Markup (B6), and Contingency Rate (B7). Maintain the Trade Hourly Wage schedule and Equipment rental tables.',
            },
            {
              step: 'Step 2',
              title: 'Create Project Master Record',
              sheet: '03_Project_Setup' as SheetTabId,
              desc: 'Generate a new unique Project ID (e.g. PRJ-2026-007), register client name, bid due date, lead estimator, and initial Draft status.',
            },
            {
              step: 'Step 3',
              title: 'Populate Quantity Takeoff (Takeoff / BOQ)',
              sheet: '04_Quantity_Takeoff' as SheetTabId,
              desc: 'Select the Project ID and input drawing takeoff lines: Division, item description, unit, quantity, material price, labor hours, and equipment rate. Applied labor rates auto-populate.',
            },
            {
              step: 'Step 4',
              title: 'Audit Dynamic Calculation Engine',
              sheet: '05_Estimate_Engine' as SheetTabId,
              desc: 'Review the live calculation of Direct Costs, Overhead Allocation, Contingency Reserve, Target Margin, and Line Item Final Bid prices.',
            },
            {
              step: 'Step 5',
              title: 'Generate Single Project Bid Summary & Sign-off',
              sheet: '06_Bid_Summary' as SheetTabId,
              desc: 'Select target Project ID to review the aggregated proposal price, division breakdowns, and labor intensity ratio for executive pricing sign-off.',
            },
            {
              step: 'Step 6',
              title: 'Track Bid Outcome & Contract Variance',
              sheet: '07_Bid_Tracker' as SheetTabId,
              desc: 'Update project lifecycle status (Won / Lost / Submitted). Record actual negotiated contract value and capture loss reasons for historical calibration.',
            },
            {
              step: 'Step 7',
              title: 'Review Executive Pipeline Health',
              sheet: '08_Dashboard' as SheetTabId,
              desc: 'Monitor company-wide win rate, active bidding volume, margin spread, and trade exposure matrix on the executive dashboard.',
            },
          ].map((item, idx) => (
            <div
              key={idx}
              className="flex items-start gap-4 p-3.5 rounded-lg border border-slate-100 hover:border-slate-300 transition"
            >
              <div className="px-2.5 py-1 rounded bg-slate-100 text-[var(--color-primary)] font-mono text-xs font-bold shrink-0">
                {item.step}
              </div>
              <div className="flex-1">
                <div className="flex items-center justify-between">
                  <h4 className="text-xs font-semibold text-[var(--color-primary)]">{item.title}</h4>
                  <button
                    onClick={() => onNavigate(item.sheet)}
                    className="text-[11px] font-medium text-[var(--color-accent)] hover:underline flex items-center gap-1 cursor-pointer"
                  >
                    <span>Open {item.sheet}</span>
                    <ArrowRight className="w-3 h-3" />
                  </button>
                </div>
                <p className="text-xs text-[var(--color-body-text)] mt-1">{item.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Frequently Asked Questions */}
      <div className="bg-[var(--color-surface)] p-6 rounded-[var(--radius-lg)] shadow-[var(--shadow-sm)] border border-slate-100">
        <h3 className="text-base font-bold font-heading text-[var(--color-primary)] mb-4 flex items-center gap-2">
          <HelpCircle className="w-4 h-4 text-[var(--color-accent)]" />
          Technical FAQ & Operational Notes
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
          <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200">
            <h5 className="font-semibold text-[var(--color-primary)] mb-1">
              Q1: How does Applied Labor Rate matching work?
            </h5>
            <p className="text-[var(--color-body-text)] leading-relaxed">
              When entering a division/trade in Sheet 04, the system performs an exact or partial lookup against Sheet 02’s Trade Wage table. If no override is provided, it uses the standard hourly rate. You can also specify an override labor rate per row.
            </p>
          </div>

          <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200">
            <h5 className="font-semibold text-[var(--color-primary)] mb-1">
              Q2: Where is my data saved and how do I back up?
            </h5>
            <p className="text-[var(--color-body-text)] leading-relaxed">
              All modifications auto-save directly to your browser's persistent localStorage. Use the top navigation's <strong>Export</strong> button to download a complete JSON backup file, or <strong>Import CSV</strong> to load bulk takeoff items from Excel.
            </p>
          </div>

          <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200">
            <h5 className="font-semibold text-[var(--color-primary)] mb-1">
              Q3: What is the formula for Total Bid Price?
            </h5>
            <p className="text-[var(--color-body-text)] leading-relaxed">
              Direct Cost = (Qty × Mat) + (Qty × LaborHrs × LaborRate) + (Qty × Equip).
              Overhead = Direct × OH%.
              Contingency = (Direct + Overhead) × Cont%.
              Markup = (Direct + Overhead + Contingency) × Markup%.
              Final Bid = Direct + Overhead + Contingency + Markup.
            </p>
          </div>

          <div className="p-3.5 rounded-lg bg-slate-50 border border-slate-200">
            <h5 className="font-semibold text-[var(--color-primary)] mb-1">
              Q4: Can I import real Excel Takeoffs?
            </h5>
            <p className="text-[var(--color-body-text)] leading-relaxed">
              Yes. Click <strong>Import CSV</strong> in the top toolbar. You can download a pre-formatted template or drag and drop your exported CSV spreadsheet directly into the application.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
